Markdown template support
xlab-steampunk/ansible-doc-extractor pull request #6
Opened 2020-03-23 21:14 UTC by agarthetiger

PR for preview and discussion of possible implementation of markdown support. This is not ready for merge yet.

Added .gitignore for PyCharm files, plus other files generated when using `pip install -e .` to test the code locally.
md_ify still needs transforming for all elements.
module.md.j2 included for reference, not necessarily for inclusion in final release. It would need a flag to switch between this and the default .rst template, as it would be tricky to pass the full path to this file after this package is installed via pip.

2020-03-24 20:31 UTC, tadeboro commented on src/ansible_doc_extractor/cli.py
> +        env.filters[extension + "_ify"] = globals()[extension + "_ify"]
There is no need for this. We can always register all our custom filters no matter what kind of template user is providing us with.

2020-03-24 20:44 UTC, tadeboro commented on src/ansible_doc_extractor/cli.py
> +    env.filters["ensure_list"] = ensure_list
While I do not mind adding yet another filter into the mix, I would much rather work towards a more strict specification of what the templates receive as data. For example, making sure that all descriptions are actually lists of paragraphs, same for authors, etc. This way all the heavy lifting can be done in a programming language, not a templating language.

2020-04-01 13:30 UTC, agarthetiger commented on src/ansible_doc_extractor/cli.py
> +        env.filters[extension + "_ify"] = globals()[extension + "_ify"]
Fair point, I'll update to always register both.

2020-04-01 13:31 UTC, agarthetiger commented
Apologies for the delay. A member of my family passed away last week (not covid-related). I'll pick this up again next week. Thank you for the feedback.

2020-04-01 19:12 UTC, tadeboro commented
Please accept our deepest condolences to you and your family. And do not worry about this PR, you are not blocking anyone's work, so please, do take care of important things first.

2020-07-01 21:10 UTC, agarthetiger commented on src/ansible_doc_extractor/cli.py
> +    env.filters["ensure_list"] = ensure_list
I've removed this now.

2020-07-01 21:14 UTC, agarthetiger commented
Thank you for your patience, I'm back looking at this again now. 
I've added a --markdown flag to the args as I couldn't see another way to switch to using an embedded markdown template. I see there is support for passing any other template, so I also wanted to check if you still wanted a default markdown template as part of this tool? If so, I'm happy to change how we switch between rst (still the default) and the bundled markdown template.

2021-03-10 19:08 UTC, faupol3 commented
@tadeboro any updates on reviewing this? Let me know if I can be of help, I'm interested in this feature as well

2021-03-10 21:25 UTC, tadeboro commented
I will be honest with you all: I completely forgot about this pull request and I feel really bad for dropping the ball. I will review this PR by the end of the week. Thank you, @faupol3, for the reminder.

2022-01-11 20:47 UTC, SirUli commented
@tadeboro any chance to get that review by the end of any week soon? Thanks in advance!

2022-01-19 11:41 UTC, juremedvesek requested changes
Merge conflicts should be simple to solve .

2022-01-19 11:41 UTC, juremedvesek commented on src/ansible_doc_extractor/templates/module.md.j2
> +    {{ "  " * level }}{{ spec.description | md_ify }}
Spec description is a list - that change fixes it. 

```suggestion
{% for desc_line in spec.description  %}
    {{ "  " * level }}{{ desc_line | md_ify }}
{% endfor %}
```

2022-01-19 12:55 UTC, SirUli commented
@agarthetiger could you please consider these requested changes for your code? Thanks in advance! I'd really like to see MD support soon :)

2022-01-20 08:11 UTC, juremedvesek approved these changes
Some polishing of template is still needed. But would be done as iterative process.

2022-01-20 08:12 UTC, merged